# Generated by Django 6.0 on 2025-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Pedido Recibido'), ('preparacion', 'En Preparación'), ('despacho', 'En Despacho'), ('entregado', 'Entregado')], default='recibido', max_length=20),
        ),
    ]
