# Generated by Django 6.0 on 2025-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pedido_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('motivo', models.CharField(choices=[('consulta', 'Consulta General'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('felicitacion', 'Felicitaciones'), ('reserva', 'Reserva de Mesa')], default='consulta', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
